# Generated by Django 4.2.7 on 2026-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_learningmodule_user_alter_course_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoringsession',
            old_name='join_link',
            new_name='join_url',
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
