# Generated by Django 4.2.7 on 2026-05-02 23:35

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_zoom_meeting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoringsession',
            old_name='mentor',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='time',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='slug',
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='topic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='start_time',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
