# Generated by Django 6.0.4 on 2026-05-04 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], db_index=True, help_text='Whether this line was produced by the customer or the assistant.', max_length=10)),
                ('content', models.TextField(help_text='Raw message body.')),
                ('intent', models.CharField(blank=True, db_index=True, help_text='Classifier / router output (e.g. order_status, refund_request).', max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='Authenticated customer who sent or received this turn.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
